# Homebrew taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# Git tools
brew "git"
brew "git-secrets"
brew "gh"
brew "ghq"

# Text editor
brew "emacs"

# Multimedia tools
brew "ffmpeg"

# Shell enhancements
brew "starship"
brew "fzf"

# File utilities
brew "wget"
brew "bat"
brew "exa"

# System monitoring tools
brew "htop"

# Databases
brew "postgresql"
brew "sqlite"

# Data manipulation tools
brew "jq"

# Desktop applications
cask "docker"
cask "discord"
cask "google-chrome"
cask "zoom"
cask "slack"
cask "spotify"
cask "appcleaner"
cask "visual-studio-code"
cask "karabiner-elements"
cask "deepl"
cask "iina"
cask "maccy"
cask "monitorcontrol"
cask "runjs"
cask "gitify"
cask "warp"
