[tools]
node = "latest"
go = "latest"
python = "latest"
uv = "latest"
bun = "latest"
deno = "latest"
ni = "latest"
pnpm = "latest"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
